spring:
  application:
    name: EurekaClient
     
 
---
eureka:
  instance:
    appname: EurekaClient
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8000  