version: '3.3'
services:
    postgres:
        image: postgres:11
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: Megabit
            POSTGRES_USER: MegabitUser
            POSTGRES_PASSWORD: Megabit
        restart: always