version: '3.7'
services:
    db:
        image: postgres:11
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: Megabit
            POSTGRES_USER: MegabitUser
            POSTGRES_PASSWORD: Megabit
        networks:
            - eureka-network
    eureka-server:
        image: darkmode1012/eureka:eureka-server
        ports:
            - 8761:8761
        networks:
            - eureka-network
    eureka-client:
        image: darkmode1012/eureka:eureka-client
        depends_on:
            - db
            - eureka-server
        ports:
            - 8000:8000
        restart: always
        networks:
            - eureka-network

networks: 
  eureka-network:
    driver: bridge