### Create entity
POST http://localhost:8080/products
Content-type: application/json
{
	"name": "toDocker1",
	"count": 22,
	"price": "100.75",
	"link": "/pretend/it/is/a/link",
	"type": "default",
	"manufacturer": "Vasya"
}

### Update entity
PUT http://localhost:8080/products/{entityId}
Content-type: application/json
{
	"name": "UpdatedProduct",
	"count": 10,
	"price": "1.5",
	"link": "pff",
	"type": "-",
	"manufacturer": "-"
}

### Fetch entities
GET http://localhost:8080/products

### Fetch entity
GET http://localhost:8080/products/{entityId}

### Delete entity
DELETE http://localhost:8080/products/{entityId}

### Update configs for Api-gateway only (or any eureka-client, but you should get internal ip address from eureka-server)
POST http://localhost:8080/actuator/refresh

### Update configs for api-gateway and all clients
POST http://localhost:8080/actuator/bus-refresh

### Get configs for Api-gateway (or any eureka-client, but you should get internal ip address from eureka-server)
GET http://localhost:8080/configs